### ISSUE TITLE
Best practice for Redshift's "Maintenance Window"

### ISSUE THREAD

**Issue by Kakakakakku** [hapyrus/fluent-plugin-redshift#22]
Hi, thank you for good plugin.

Today, I have a question.
Please tell me that best practice for Redshift's "Maintenance Window".

* http://aws.amazon.com/redshift/faqs/?nc2=h_ls#maintenance

Sometimes, it was an error like bellow because plugin can't connect to Redshift during "Maintenance Window".

```ruby
YYYY-MM-DD HH:MM:SS +0900 [error]: failed to copy data into redshift. s3_uri=s3://xxx/xxx.gz error="SSL SYSCALL error: EOF detected\n"
```

Code is here.

* https://github.com/hapyrus/fluent-plugin-redshift/blob/master/lib/fluent/plugin/out_redshift.rb#L126

My idea is to set `redshift_connect_timeout` property bigger, for example from '10' (default) to '60...300' (manual).
But, I'm not tried yet.

Please tell me if someone has good idea.
Thank you so much.

**Comment by mmasashi** [comment]
Thanks for using this plugin and reporting the issue. As you mentioned, the current code doesn't handle temporary network error including Redshift maintenance well. One idea is separating out temporary error and other critical errors like authentication failure for logging. 

Could you give us the backtrace of the error if you have? I want to know where this error happens from.

**Comment by Kakakakakku** [comment]
@mmasashi 
Thank you for your early reply.
Sure, I share my log below, but I masked some information.

* Masked S3 Path to `s3://xxx.gz`
* Masked Redshift Endpoint to `yyy.ap-northeast-1.redshift.amazonaws.com`
* Masked Fluentd InstanceID to `12345`

>Could you give us the backtrace of the error if you have?

Its are point that I think.

* At first, `PG::UnableToSend` error was occurred.
* After that, `PG::ConnectionBad` errors were occurred by Fluentd retry.
* Sending log was succeeded after 7 times retry this time.
    * Actually I don't lost my logs. :smiley:
    * So, just maybe this problem is not plugin issue I think.
* `record_reformer: NoMethodError` were occurred every day, so it has no relation with this issue.

Thank you so much.

```ruby
2015-07-29 10:36:29 +0900 [error]: failed to copy data into redshift. s3_uri=s3://xxx.gz error="SSL SYSCALL error: EOF detected\n"
2015-07-29 10:36:29 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:36:22 +0900 error_class="PG::UnableToSend" error="SSL SYSCALL error: EOF detected\n" instance=12345
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:122:in `exec'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:122:in `write'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:36:29 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:36:23 +0900 error_class="PG::ConnectionBad" error="could not connect to server: Connection refused\n\tIs the server running on host \"yyy.ap-northeast-1.redshift.amazonaws.com\" and accepting\n\tTCP/IP connections on port 5439?\n" instance=12345
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:36:29 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:36:27 +0900 error_class="PG::ConnectionBad" error="could not connect to server: Connection refused\n\tIs the server running on host \"yyy.ap-northeast-1.redshift.amazonaws.com\" and accepting\n\tTCP/IP connections on port 5439?\n" instance=12345
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:36:29 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:36:36 +0900 error_class="PG::ConnectionBad" error="could not connect to server: Connection refused\n\tIs the server running on host \"yyy.ap-northeast-1.redshift.amazonaws.com\" and accepting\n\tTCP/IP connections on port 5439?\n" instance=12345
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:36:29 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:36:33 +0900 [warn]: record_reformer: NoMethodError undefined method `to_sym' for nil:NilClass /usr/lib64/fluent/ruby/lib/ruby/1.9.1/ostruct.rb:90:in `block in initialize'
2015-07-29 10:36:37 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:36:53 +0900 error_class="PG::ConnectionBad" error="could not connect to server: Connection refused\n\tIs the server running on host \"yyy.ap-northeast-1.redshift.amazonaws.com\" and accepting\n\tTCP/IP connections on port 5439?\n" instance=12345
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:36:37 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:36:54 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:37:22 +0900 error_class="PG::ConnectionBad" error="could not connect to server: Connection refused\n\tIs the server running on host \"yyy.ap-northeast-1.redshift.amazonaws.com\" and accepting\n\tTCP/IP connections on port 5439?\n" instance=12345
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:36:54 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:37:23 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:38:20 +0900 error_class="PG::ConnectionBad" error="could not connect to server: Connection refused\n\tIs the server running on host \"yyy.ap-northeast-1.redshift.amazonaws.com\" and accepting\n\tTCP/IP connections on port 5439?\n" instance=12345
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:37:23 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:38:31 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-29 10:40:27 +0900 error_class="PG::ConnectionBad" error="timeout expired\n" instance=12345
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `initialize'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `new'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/pg-0.17.1/lib/pg.rb:40:in `connect'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:209:in `fetch_table_columns'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:161:in `create_gz_file_from_structured_data'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-redshift-0.0.4/lib/fluent/plugin/out_redshift.rb:94:in `write'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2015-07-29 10:38:31 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2015-07-29 10:40:33 +0900 [info]: completed copying to redshift. s3_uri=s3://xxx.gz
2015-07-29 10:40:33 +0900 [warn]: retry succeeded. instance=12345
2015-07-29 10:41:27 +0900 [warn]: record_reformer: NoMethodError undefined method `to_sym' for nil:NilClass /usr/lib64/fluent/ruby/lib/ruby/1.9.1/ostruct.rb:90:in `block in initialize'
2015-07-29 10:41:32 +0900 [info]: completed copying to redshift. s3_uri=s3://xxx.gz
```

**Comment by mmasashi** [comment]
@Kakakakakku Thanks for the logs, it's helpful to understand errors. It seems there are some kind of errors you were getting, but no data lost. Just logging issue which we need to fix.

**Comment by Kakakakakku** [comment]
:+1:
